# Generated by Django 4.2.7 on 2023-12-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0002_alter_jobpost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
