# Generated by Django 4.2.7 on 2023-12-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0004_alter_jobpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='expire',
            field=models.DateField(null=True),
        ),
    ]
